my_blog/article/urls.py
from django.urls import path, include
# 引入 views.py
from . import views


# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    # path 函数将url映射到视图-文章列表
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # 新增文章
    path('article-create/', views.article_create, name='article_create'),
    # 删除文章
    # path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    # 安全删除文章
    path('article-safe-delete/<int:id>/', views.article_delete, name='article_safe_delete'),
    # 更新文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    # 点赞+1
    path('increase-likes/<int:id>/', views.IncreaseLikesView.as_view(), name='increase_likes'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
# 引入 include
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from article.views import article_list


# 存放映射关系的列表
urlpatterns = [
    # 首页 http://127.0.0.1:8000/accounts/login/
    path('', article_list, name='home'),
    path('admin/', admin.site.urls),
    # 配置 app 的url, namespace可以保证反查到唯一的url
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password_reset/', include('password_reset.urls')),
    # 评论
    path('comment/', include('comment.urls', namespace='comment')),
    # 消息通知
    path('inbox/notifications', include('notifications.urls', namespace='notifications')),
    # notice
    path('notice/', include('notice.urls', namespace='notice')),
    # django-allauth
    path('accounts/', include('allauth.urls')),
]

# 上传图片路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

my_blog/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'


urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户注册
    path('register/', views.user_register, name='register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    # 修改用户信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

my_blog/templates/back_to_top_func.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

my_blog/templates/base.html
<!--
    载入静态文件
    使用 Django3 改为 {% load static %}
-->
{% load staticfiles %}

<!--<!DOCTYPE html>-->
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件-->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.min.css">
</head>
<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 新增两个 div 容器 -->
    <div class="wrapper">
        <!-- 预留具体页面的位置-->
        {% block content %}{% endblock content %}
        <div id="push"></div>
    </div>

    <!-- 引入注脚-->
    {% include 'footer.html' %}
    <!-- 引入bootstrap.js 依赖 jquery.js 和 popper.js，因此在这里引入-->
    <script src="{% static 'jquery/jquery-3.6.0.js' %}"></script>
      <!-- 在jquery后面引入 back_to_top_func.html  -->
    {% include 'back_to_top_func.html' %}

    {% block script %}{% endblock script %}
    <!-- 引入layer.js -->
    <script src="{% static 'layer/layer.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>
    <!-- 引入bootstrap的js文件 -->
    <!--    <script src="bootstrap/js/bootstrap.min.js"></script>-->
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.0.2/js/bootstrap.min.js"></script>
     <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            min-height: 100%;
            margin-bottom: -60px;
        }

        #footer,
        #push {
            height: 60px;
        }
    </style>
</body>
</html>

my_blog/templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>

<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.xiaobailong.com 2021</p>
    </div>
</footer>

my_blog/templates/header.html
<!-- 引入notifications的模板标签 -->
{% load notifications_tags %}
{% notifications_unread as unread_count %}

<!--定义导航栏-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!-- 导航栏商标-->
        <a class="navbar-brand" href="{% url 'article:article_list' %}">我的博客</a>

        <!-- 导航入口-->
        <div>
            <ul class="navbar-nav">
                <!-- 条目-->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
                </li>
<!--                 <li class="nav-item">-->
<!--                    <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>-->
<!--                 </li>-->
                <!-- Django的 if 模板语句 -->
                {% if user.is_authenticated %}
                    <!-- 如果用户已经登录，则显示用户名下拉框 -->
                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle"data-target="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" onclick="open_dropdown()">
                            <!-- 小红点 -->
                            {% if unread_count %}
                                <svg viewBox="0 0 8 8"
                                     width="8px"
                                     height="8px">
                                    <circle cx="4"
                                            cy="4"
                                            r="4"
                                            fill="#ff6b6b"
                                            ></circle>
                                </svg>
                            {% endif %}
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <!-- 通知计数 -->
                             <a class="dropdown-item" href="{% url 'notice:list' %}">通知...
                                {% if unread_count %}
                                    <span class="badge badge-danger">{{ unread_count }}</span>
                                {% endif %}
                            </a>
                            <a class="dropdown-item" href="{% url 'userprofile:edit' user.id %}">个人信息</a>
                            <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>
                            <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                        </div>
                     </li>
                <!-- 如果用户未登录，则显示 “登录” -->
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'userprofile:login' %}" class="nav-link">登录</a>
                    </li>
                <!-- if 语句在这里结束 -->
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- 删除用户 -->
{% if user.is_authenticated %}
<form
        style="display:none;"
        id="user_delete"
        action="{% url 'userprofile:delete' user.id %}"
        method="post">
    {% csrf_token %}
    <button type="submit">发送</button>
</form>

<script>
    function user_delete(){
        //调用layer弹窗组件
        layer.open({
            title: "确认删除",
            content: "确认删除用户资料吗？",
            yes: function(index, layero) {
                $('form#user_delete button').click();
                layer.close(index);
            },
        })
    }

    function open_dropdown(){
        $('.dropdown-toggle').dropdown()
    }
</script>
{% endif %}


<!--<script>-->
<!--    function open_dropdown(){-->
<!--        $('.dropdown-toggle').dropdown()-->
<!--    }-->
<!--</script>-->